apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: standalone-docs
  description: Testing Standalone documentation.
  tags:
    - documentation
    - testing
  annotations:
    backstage.io/techdocs-ref: wiki:https://github.com/wbaileydevva/hybrid-doc-test.wiki.git
    bih/techdocs-builder: local
spec:
  type: documentation
  owner: team-1
  system: system-1
  lifecycle: experimental
